# Generated by Django 5.2.17 on 2026-08-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sensormeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_brand',
            field=models.CharField(choices=[('DS18B20', 'Ds18B20'), ('resistive_soil_hum', 'Resistive Soil Hum'), ('not_specified', 'Not Spec')], default='not_specified', max_length=50),
        ),
        migrations.AddField(
            model_name='sensor',
            name='unit',
            field=models.CharField(choices=[('celsius', 'Celsius'), ('percent', 'Percent'), ('ppm', 'Ppm'), ('ph', 'Ph'), ('not_specified', 'Not Spec')], default='not_specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('soil_temperature', 'Soil Temp'), ('soil_humidity', 'Soil Hum'), ('air_temperature', 'Air Temp'), ('air_humidity', 'Air Hum'), ('co2', 'Co2'), ('ph', 'Ph'), ('light_intensity', 'Light'), ('not_specified', 'Not Spec')], default='not_specified', max_length=50),
        ),
    ]
