# Generated by Django 5.2.17 on 2026-08-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sensor_sensor_brand_sensor_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_min', models.FloatField(blank=True, help_text='Below this triggers a Warning', null=True)),
                ('warning_max', models.FloatField(blank=True, help_text='Above this triggers a Warning', null=True)),
                ('critical_min', models.FloatField(blank=True, help_text='Below this triggers Critical', null=True)),
                ('critical_max', models.FloatField(blank=True, help_text='Above this triggers Critical', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='api.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_value', models.FloatField()),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='CRITICAL', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Açık'), ('resolved', 'Çözüldü'), ('acknowledged', 'Onaylandı')], default='active', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.sensor')),
                ('threshold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sensorthreshold')),
            ],
        ),
    ]
