# Generated by Django 5.2.17 on 2026-08-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_alert_options_alert_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('soil_temperature', 'Soil Temp'), ('soil_humidity', 'Soil Hum'), ('air_temperature', 'Air Temp'), ('air_humidity', 'Air Hum'), ('co2', 'Co2'), ('ph', 'Ph'), ('light_intensity', 'Light'), ('not_specified', 'Not Spec')], default='not_specified', max_length=100)),
                ('unit', models.CharField(choices=[('celsius', 'Celsius'), ('percent', 'Percent'), ('ppm', 'Ppm'), ('ph', 'Ph'), ('not_specified', 'Not Spec')], default='not_specified', max_length=100)),
                ('period', models.FloatField(blank=True, default=5.0, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_brand',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='unit',
        ),
        migrations.AddField(
            model_name='sensor',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sensors', to='api.sensorprofile'),
        ),
    ]
